### ISSUE TITLE
Find diameter of a Binary tree in cpp

### ISSUE THREAD

**Issue by ary1733** [ary1733/Hacktober2020#27]

**Comment by ankitsri98** [comment]
Yes , i can Solve this Problem . Please assign this to me.
Thank you

**Comment by ankitsri98** [comment]
Sir This is my first time solving a doubt.
i have written the code
should i copy paste the code in the comment section
or attach a link to it .

**Comment by ary1733** [comment]
@ankitsri98  You should follow these steps to complete your pull request:
1)fork the repository
2)add a file "TreeDia.cpp" in CPP folder in the forked repository 
3)paste your code inside the new file.
4)Create a pull request with commit message "Added  "TreeDia.cpp" in CPP"

and then i will merge it to the main branch

**Comment by ary1733** [comment]
you could refer to this https://hacktoberfest.digitalocean.com/ to learn how to create your first pull request.

**Comment by ankitsri98** [comment]
ok sir got it thanks
