### ISSUE TITLE
Implement segment tree to find sum of segment in python

### ISSUE THREAD

**Issue by ary1733** [ary1733/Hacktober2020#29]
queries
Find the sum of segment l to r
update i th element

**Comment by KoushikSahu** [comment]
I want to work on this issue. Please assign it to me.

**Comment by KoushikSahu** [comment]
I want to work on this issue. Please assign it to me.

**Comment by KoushikSahu** [comment]
@ary1733 I have made a PR to resolve this issue. Please review it.
