### ISSUE TITLE
Implement calculator in python

### ISSUE THREAD

**Issue by ary1733** [ary1733/Hacktober2020#31]

**Comment by shubhamnag14** [comment]
can i do this job..

**Comment by sashpawar11** [comment]
Hello, can you assign this task to me @ary1733 !

**Comment by ary1733** [comment]
@shubhamnag14 ,sure

**Comment by ary1733** [comment]
@sashpawar11 ,sure

**Comment by PravunathSingh** [comment]
Hey @ary1733 this seems like an interesting problem, can you please assign me this issue?

**Comment by ary1733** [comment]
@PravunathSingh  sure

**Comment by muhesh-kumar** [comment]
Hello @ary1733! I'd like to contribute. Can you assign me this issue, please?

**Comment by ghanender-chauhan** [comment]
Hii @ary1733  I want to work on this issue please assign me this task..
thanks

**Comment by ary1733** [comment]
I have already got three pull request for this ,hence i am closing this.
