### ISSUE TITLE
Add dfs in cpp

### ISSUE THREAD

**Issue by ary1733** [ary1733/Hacktober2020#4]

**Comment by Rares-AndreiVasiu** [comment]
-[stackoverflow documentation](https://stackoverflow.com/questions/39708305/dfs-implementation-in-c-using-adjacency-list-using-vector-and-linked-list)

-[geeksforgeeks documentation](https://www.geeksforgeeks.org/depth-first-search-or-dfs-for-a-graph/)

**Comment by ary1733** [comment]
do you want to contribute and create a pull request @Rares-AndreiVasiu ?

**Comment by ZarghamDanial** [comment]
Hey, is this still open?

**Comment by ary1733** [comment]
yes @ZarghamDanial

**Comment by ZarghamDanial** [comment]
Can i work on this?

**Comment by ary1733** [comment]
> Can i work on this?

Yes sure
